- hosts: vcenter
  tasks:
  - name: Create a snapshot1
    community.vmware.vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      folder: "/{{ datacenter_name }}/"
      name: DC1
      state: absent
      snapshot_name: test
      validate_certs: no
    delegate_to: localhost

    

